### ISSUE TITLE
[Bug]: Model deployment: path not correctly trimmed when editing

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/odh-dashboard#1173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a model located at the root of a bucket. With the new UI that was recently deployed, the leading / is built-in so I did not enter anything for the model path. And the model loaded successfully.

However, when I go to edit this deployment (to check the configuration for example), the leading `/` appears also in the input box.
![image](https://user-images.githubusercontent.com/3944034/234044802-beb65ca9-3127-402b-9bee-3b1e884a0f62.png)

### Expected Behavior

Folder path should only list the buil-in leading `/`. It should not appear in the input box.

**Comment by lucferbux** [comment]
Did we actually fix that right @Gkrumbach07 ? If so we can close this issue.

**Comment by andrewballantyne** [comment]
No we did not @lucferbux -- this is on Edit.

**Comment by manaswinidas** [comment]
I think this is solved. I don't see a leading`/` in the input box now.
<img width="796" alt="Screenshot 2023-07-12 at 5 13 22 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22885912/e1911c3d-62bb-4d56-aada-f8aaf1e14963">

**Comment by andrewballantyne** [comment]
Create a Model, then edit it @manaswinidas -- that looks like you're just creating.

**Comment by lucferbux** [comment]
@manaswinidas what's the progress on this?

**Comment by manaswinidas** [comment]
@lucferbux just submitted a fix

**Comment by manosnoam** [comment]
After editing first time a saved model, then the leading slash is only shown on the left, and removed from the original path.
However, if user tries to edit the model on a second time, saves and edits again, then it UI still shows the slash twice:
![image](https://github.com/opendatahub-io/odh-dashboard/assets/9913945/befacf67-e022-4fea-aa10-066b160306ef)

If the leading slash should always appear, then in case user update the path with a leading slash, it should be trimmed in the saved value, so it will not be duplicated when re-editing.

**Comment by andrewballantyne** [comment]
@manosnoam Definitely looks like a gap here... I'm going to log something new and we can figure out the proper solution on that ticket.
