### ISSUE TITLE
[Bug]: Cluster storage size modification is not saved

### ISSUE THREAD

**Issue by manosnoam** [opendatahub-io/odh-dashboard#1876]
Modifying an existing cluster storage size is not saved.
Reproduced in RHODS 1.33 dashboard both on Firefox and Chrome.

_Originally posted by @manosnoam in https://github.com/opendatahub-io/odh-dashboard/issues/1564#issuecomment-1738874595_

**Comment by manosnoam** [comment]
https://github.com/opendatahub-io/odh-dashboard/assets/9913945/5accc747-0211-43ce-ae1e-280c6538f9c9

**Comment by shalberd** [comment]
this can also depend on the storageClass used, by the way, have you looked at the events of the PersistentVolumeClaim and PV? The storageClass in use (default storage class of cluster or explicitely mentioned in PVC yaml) must allow Volume expansion `allowVolumeExpansion: true`

**Comment by DaoDaoNoCode** [comment]
Hi @manosnoam I believe this issue is duplicated with https://github.com/opendatahub-io/odh-dashboard/issues/1565, and it's already fixed in https://github.com/opendatahub-io/odh-dashboard/pull/1714 but running on the feature branch `f/ds-projects`.

**Comment by manosnoam** [comment]
![image](https://github.com/opendatahub-io/odh-dashboard/assets/9913945/9a40ec96-4885-4f82-bb22-6f46626fb869)

But as you expected:
![image](https://github.com/opendatahub-io/odh-dashboard/assets/9913945/5cfd20a9-cf74-42e5-bf8f-3748cd5000e3)

Is #1565 targeted to be resolved in 1.34 ?

**Comment by andrewballantyne** [comment]
@manosnoam Nope, #1565 is not in the next RHODS release.

If you look at the associated PR to the issue, you can see this merged into `f/ds-projects` -- a feature branch. Only things merged into `main` go to RHODS.

![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/332c0ac6-3d52-472a-bdd8-8f1fa4d6b873)

**Comment by andrewballantyne** [comment]
> @andrewballantyne this can also depend on the storageClass used...

@shalberd Great point. I've added it to #1270 as a comment for when we pick that up.

**Comment by andrewballantyne** [comment]
@christianvogt I recall seeing a comment somewhere, might be a merged PR might be a feature branch commit. I thought we moved from status to spec for displaying values as this is requested state not resolved state (which I think doesn't do anything unless the PVC is attached). 

Not sure who did the actual work though 🤔

**Comment by DaoDaoNoCode** [comment]
@andrewballantyne it's https://redhat-internal.slack.com/archives/C043A9D5DMW/p1694530505702999 from our archived slack channel.

**Comment by andrewballantyne** [comment]
Ah which are issues:
- https://github.com/opendatahub-io/odh-dashboard/issues/1565
- https://github.com/opendatahub-io/odh-dashboard/issues/1480

from the PR https://github.com/opendatahub-io/odh-dashboard/pull/1714 -- which is merged into `f/ds-projects` so not in main or RHODS 1.33. @manosnoam

**Comment by andrewballantyne** [comment]
Which I already said 🤦 too many things to track. I think we can close this issue -- but we can wait for triage on Monday.

**Comment by Gkrumbach07** [comment]
/close

this was solved in a feature branch and this ticket is a duplicated

see [comment](https://github.com/opendatahub-io/odh-dashboard/issues/1876#issuecomment-1741283417)
